# Generated by Django 4.2.5 on 2023-09-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edictai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=1, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='audio',
            field=models.FileField(blank=1, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='script',
            field=models.TextField(blank=1),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=1, upload_to='video/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='images',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edictai_app.videos'),
        ),
    ]
