# Generated by Django 4.2.5 on 2023-09-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edictai_app', '0002_images_videos_audio_alter_videos_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Videoclips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoclip', models.FileField(upload_to='videoclips/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edictai_app.videos')),
            ],
        ),
    ]
