# Generated by Django 4.1.7 on 2023-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edictai_app', '0003_videos_timestamp_videoclips'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='link',
            field=models.CharField(blank=1, max_length=200),
        ),
    ]
