# Generated by Django 4.1.7 on 2023-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edictai_app', '0004_videos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
